### ISSUE TITLE
Remove Less

### ISSUE THREAD

**Issue by BasixKOR** [reflation/extension#21]
less 파일이 하나밖에 포함되어 있지 않고 이 역시 타 CSS 파일을 불러오는 데 사용되는 것으로 보아 제거 시 빌드 타임 향상 등의 효과를 기대할 수 있을 것 같습니다.

추가로 use/gh-actions 에서 실험 중인 GitHub Actions의 yarn audit도 통과할 수 있을 것 같아요!

**Comment by x86chi** [comment]
또한 #app 스타일 리셋을 reconstruction.ts 이나 index.html의 인라인 스타일로 맞겼는데 요 부분은 reset.css 에 정적으로 놓아도 가능하네요. less 제거할 때 같이 패치 합시다.

**Comment by x86chi** [comment]
흠.. 그냥 따로 PR 올리는 편이 나아 보이네요.
