### ISSUE TITLE
WarningLabel component always receive a Result.blocked

### ISSUE THREAD

**Issue by x86chi** [reflation/extension#28]
> [처음 언급했던 코멘트 링크](https://github.com/reflation/extension/commit/405e1d2d684530429b3521a15a0b87ab650bf588#r36647833)

https://github.com/reflation/extension/blob/42f3626f56cc90d1581c0adbb8bde141cec697ed/src/app/components/Label.tsx#L16-L24

`Result.invalid` 대신에 무조건 `Result.blocked`를 속성으로 넘겨받고 있습니다.

memo를 안해도 해당 버그는 여전하네요.

**Comment by BasixKOR** [comment]
![image](https://user-images.githubusercontent.com/7413880/71797266-9c10ec00-3090-11ea-9c4f-0b3dc56b405d.png)
제 환경에서는 AJAX Response가 비어있는 것으로 표시됩니다. axios 요청 이후 코드가 아예 실행되지 네요...
