### ISSUE TITLE
Implement Logout UI

### ISSUE THREAD

**Issue by x86chi** [reflation/extension#33]
## `manifest.json`

```json
{
  "run_at": "document_end",
  "matches": ["https://dreamy.jejunu.ac.kr/frame/sysLeftmenu.do"],
  "js": ["logout.js"]
}
```

## `logout.js`

```
document
  .querySelector('td[valign="bottom"][align="right"]')
  .addEventListener('click', localStorage.clear)
```

기존 로그아웃 UI를 클릭하면 localStorage 또한 비워지게 생각해봤는데 리스너가 바인딩이 안되네요.. 일단 이슈로 Draft 하면 괜찮을 것 같아 올려봅니다.

**Comment by BasixKOR** [comment]
개발 도중 일부 특이한 사항이 발견되어 기록 차 작성합니다.

# YUI가 레이아웃을 재구성합니다
document_idle, 즉 document.readyState가 complete가 된 이후의 DOM은 아래와 같은 형태이며, 우리가 click 이벤트를 걸고자 하는 버튼이 있는 iframe은 `div#left1` 에 존재합니다.

![image](https://user-images.githubusercontent.com/7413880/71983156-7ee34580-3269-11ea-8694-13952dbce74a.png)

다만 left1 내에 존재하는 버튼에 이벤트를 달아도 이후 left1은 YUI에 의해 제거되며 `div#layout-doc`에 레이아웃이 모두 옮겨집니다. (DOM Mutation Breakpoint를 달았을 때 append 함수가 nodeRemoval breakpoint를 호출하는 것을 보아 append를 통해 body로 옮겨짐을 확인했습니다만 div를 통해 옮겨지는 부분은 아직 확인하지 못했습니다.)

**Comment by x86chi** [comment]
꽤 오래 걸린다면 다음 MVP로 보류하셔도 괜찮습니다.
