### ISSUE TITLE
Fails to parse TSX in test environment

### ISSUE THREAD

**Issue by x86chi** [reflation/extension#57]
Trying to run tests with Jest in a Preact app with TypeScript :

```
FAIL  src/app/app.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, 
     e.g. it's not plain JavaScript.
...
    Details:

    src/app/app.test.tsx:10
        const wrapper = enzyme_1.mount(<app_1.default optOutUrl="none"/>);
                                       ^

    SyntaxError: Unexpected token <

    at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1059:14)
```

After seen [TypeScript example](https://github.com/preactjs/enzyme-adapter-preact-pure/tree/master/examples/typescript) in this enzyme-adapter-preact-pure, I Changing jsx option to react in `tsconifg.json`. But It not helpful for my project environment:
```
Cannot find module 'react' from 'styled.js'

    However, Jest was able to find:
        './styled.js'
        './styled.js.flow'
        './styled.js.map'

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:276:11)
      at Object.<anonymous> (node_modules/linaria/src/react/styled.js:3:15)
```

In the above error, it says that react parsing failed in the styled component related file.

I also tried using babel-jest with below config. But I got the same message as the first error log.

```
“transform”: {
      “^.+\\.ts$”: “babel-jest”
    }
```

I also asked other community:
- https://github.com/preactjs/enzyme-adapter-preact-pure/issues/97
- https://stackoverflow.com/questions/60348539/jest-fails-to-parse-tsx-in-preact

**Comment by x86chi** [comment]
I added the [`preact/compat` alias](https://preactjs.com/guide/v10/getting-started#aliasing-in-jest) to `moduleNameMapper` in jest config, but the result is same.

**Comment by x86chi** [comment]
```
“transform”: {
      “^.+\\.ts$”: “babel-jest”
    }
```

babel-jest 를 쓰는 경우에서 뒤늦게 위 정규식에 tsx를 추가했는데 react 모듈을 찾지 못한다고 하네요.

```
 FAIL  src/app/app.test.tsx
  ● Test suite failed to run

    src/app/app.tsx: Cannot find module 'react'
```

**Comment by BasixKOR** [comment]
Webpack은 TypeScript 실행 이후 Babel을 쓰는데, ts-jest에서는 그런 설정을 적용하기가 쉽지 않네요... babel-jest에 별도 Babel config를 주어 TypeScript 프리셋을 주거나 아예 프로젝트를 Babel만 사용하도록 조정해야 할 것 같아요.

**Comment by x86chi** [comment]
전자의 config 은 `@babel/preset-typescript` 만 추가했을 때와 어떤 차이점이 있나요?

**Comment by x86chi** [comment]
아.. 제가 위 질문을 한 이유가 마지막에 올린 에러가 타입스크립트 프리셋을 추가한 결과라 그렇습니다.

**Comment by BasixKOR** [comment]
타입스크립트 프리셋을 추가해도 다른 오류가 나는 거군요 😢 moduleNameMapper 등을 설정해도 react를 못 찾는 게 저는 버그가 아닌가 의심이 됩니다.

**Comment by BasixKOR** [comment]
별개의 이야기이지만 ts-jest에서 `babelConfig` 옵션을 주어서 babel-jest를 TypeScript 컴파일 후에 실행이 가능하더군요! https://kulshekhar.github.io/ts-jest/user/config/babelConfig

**Comment by x86chi** [comment]
알겠습니다. 리듀서와 액션만이라도 테스트를 작성해서 지표를 가늠하게 하는 게 지금으로선 최선인 것 같네요.

**Comment by x86chi** [comment]
말씀해주신 대로 babel-config 설정을 추가하니 기존 빌드 환경을 잘 따라 주네요.

차이점이라면 `transform`으로 babel-jest 를 직접적으로 명시 하지 않고 `ts-jest` 프리셋을 그대로 사용했습니다.

```
"preset": "ts-jest",
    "globals": {
      "ts-jest": {
        "babelConfig": true
      }
    },
```

**Comment by x86chi** [comment]
#57에서 작업 이어갑니다.
