### ISSUE TITLE
Switch to CSS-in-JS libraries

### ISSUE THREAD

**Issue by BasixKOR** [reflation/extension#6]
_Originally discussed by @x86chi in https://github.com/reflation/extension/pull/1#issuecomment-569949977_

**Comment by x86chi** [comment]
> https://codepen.io/betaflsh/pen/xxbPxbm

```
span{
  font-size: 25px;
  font-family: sans-serif;
  color: red;
  animation: blink 1s linear 1;
}

@keyframes blink{
  0%{opacity: 0;}
  50%{opacity: .5;}
  100%{opacity: 1;}
}
```

위와 같이 미디어 쿼리나 키프레임 구문을 사용하기 위해서는 문자열로 읽어 들이는 방식이 필요합니다.

**Comment by BasixKOR** [comment]
이후 익스텐션 번들의 사이즈를 고려했을 때 [Linaria](https://linaria.now.sh/)를 사용해보는 건 어떨까요?

**Comment by x86chi** [comment]
네, 괜찮겠네요! 혹시 해당 패치 작업을 해주실 수 있으신가요?
